import os
from os import sep as SEP

# Folders
PROJECT_PATH = os.path.normpath(os.getcwd() + os.sep + os.pardir)

SCRIPTS_FOLDER = "utils"
SCRIPTS_PATH = PROJECT_PATH + SEP + SCRIPTS_FOLDER

DATA_FOLDER = "data"
DATA_PATH = PROJECT_PATH + SEP + DATA_FOLDER

# Scripts
TOKENIZER = "tokenizer.perl"
TOKENIZER_PATH = SCRIPTS_PATH + SEP + "tools" + SEP + TOKENIZER

# Train files
RAW_TRAIN = "raw_train.json"
RAW_TRAIN_PATH = DATA_PATH + SEP + RAW_TRAIN

TOKENIZED_TRAIN = "tokenized_train.json"
TOKENIZED_TRAIN_PATH = DATA_PATH + SEP + TOKENIZED_TRAIN

EMBEDDED_TRAIN = "embedded_train.json"
EMBEDDED_TRAIN_PATH = DATA_PATH + SEP + EMBEDDED_TRAIN

INDEX2WORD = "index2word.npy"
INDEX2WORD_PATH = DATA_PATH + SEP + INDEX2WORD

# Embeddings
ALL_EMBEDDING = "wiki.simple.bin"
ALL_EMBEDDING_PATH = DATA_PATH + SEP + ALL_EMBEDDING

TRAIN_EMBEDDING = "train_embedding.npy"
TRAIN_EMBEDDING_PATH = DATA_PATH + SEP + TRAIN_EMBEDDING

# Model
MODEL = "model"
MODEL_PATH = DATA_PATH + SEP + MODEL

'''
RAW_EMBEDDING = "wiki-news-300d-1M-subword.vec"
RAW_EMBEDDING_PATH = DATA_PATH + SEP + RAW_EMBEDDING

EMBEDDING = "embedding.npy"
EMBEDDING_PATH = DATA_PATH + SEP + EMBEDDING

VOCABULARY = "vocabulary.npy"
VOCABULARY_PATH = DATA_PATH + SEP + VOCABULARY
'''
