import os
from os import sep as SEP

# Folders
PROJECT_PATH = os.path.normpath(os.getcwd() + os.sep + os.pardir)

SCRIPTS_FOLDER = "utils"
SCRIPTS_PATH = PROJECT_PATH + SEP + SCRIPTS_FOLDER

DATA_FOLDER = "data"
DATA_PATH = PROJECT_PATH + SEP + DATA_FOLDER

LOGS_FOLDER = "logs"
LOGS_PATH = PROJECT_PATH + SEP + LOGS_FOLDER

# Scripts
TOKENIZER = "tokenizer.perl"
TOKENIZER_PATH = SCRIPTS_PATH + SEP + "tools" + SEP + TOKENIZER

# Train-test files
RAW_TRAIN = "raw_train.json"
RAW_TRAIN_PATH = DATA_PATH + SEP + RAW_TRAIN
RAW_TEST = "raw_test.json"
RAW_TEST_PATH = DATA_PATH + SEP + RAW_TEST

TOKENIZED_TRAIN = "tokenized_train.json"
TOKENIZED_TRAIN_PATH = DATA_PATH + SEP + TOKENIZED_TRAIN
TOKENIZED_TEST = "tokenized_test.json"
TOKENIZED_TEST_PATH = DATA_PATH + SEP + TOKENIZED_TEST

EMBEDDED_TRAIN = "embedded_train.json"
EMBEDDED_TRAIN_PATH = DATA_PATH + SEP + EMBEDDED_TRAIN
EMBEDDED_TEST = "embedded_test.json"
EMBEDDED_TEST_PATH = DATA_PATH + SEP + EMBEDDED_TEST

COMFORT_TRAIN = "comfort_train.npz"
COMFORT_TRAIN_PATH = DATA_PATH + SEP + COMFORT_TRAIN
COMFORT_TEST = "comfort_test.npz"
COMFORT_TEST_PATH = DATA_PATH + SEP + COMFORT_TEST

INDEX2WORD = "index2word.npy"
INDEX2WORD_PATH = DATA_PATH + SEP + INDEX2WORD

# Embeddings
ALL_EMBEDDING = "wiki.simple.bin"
ALL_EMBEDDING_PATH = DATA_PATH + SEP + ALL_EMBEDDING

KNOWN_EMBEDDING = "known_embedding.npy"
KNOWN_EMBEDDING_PATH = DATA_PATH + SEP + KNOWN_EMBEDDING

# Model
MODEL = "model"
MODEL_PATH = DATA_PATH + SEP + "model" + SEP + MODEL

